interface trade-handler {
  use types.{trade};
  update-iv: func (user-email: string, group-ids: list<string>) -> bool;
  active-positions: func (user-email: string, party-a: u8, party-b: option<list<u8>>, pair-id: u8>) -> list<trade>;
}
