interface types {
  use jabratech:common/types.{pair, currency, option-kind, side, option-type, payout-ccy, instrument-kind, counterparty, user};

  record trade {
    id: s64,
    date-created: string,
    date-updated: option<string>,
    venue-instrument-name: string,
    venue-order-id: string,
    venue-trade-id: string,
    amount: f64,
    price: f64,
    instrument-name: string,
    instrument-kind: instrument-kind,
    strike: f64,
    index-price: f64,
    iv: f64,
    expiry-timestamp: string,
    fee-amount: option<f64>,
    option-kind: option-kind,
    side: side,
    interest-rate: f64,
    group-id: string,
    px-in-base-ccy: f64,
    px-in-quote-ccy: f64,
    spot: f64,
    has-termsheet: bool,
    is-submitted: bool,
    payout-ccy: payout-ccy,
    option-type: option-type,
    trade-status: trade-status,
    has-instrument: bool,
    trade-type: trade-type,
    pnl: option<f64>,
    pnl-ccy: option<string>,
    activity: trade-activity,
    pnl-ccy-ticker: option<string>,
    payout-ccy-ticker: option<string>,
    r1: option<f64>,
    r2: f64,
    ttm: f64,
    user-created: user,
    counterparty-id: counterparty,
    pair-id: pair,
    base-currency-id: currency,
    quote-currency-id: currency,
    fee-currency-id: option<currency>,
    party-a: counterparty,
    party-b: counterparty,
    ccy-id: currency,
    current-ttm: f64,
  }

  /**
   * Enum representing the status of a trade
   * - open: trade is open
   * - expired: trade has expired
   * - exercised: trade has been exercised
   * - closed: trade is closed
   */
  enum trade-status {
    open,
    expired,
    exercised,
    closed
  }

  /**
   * Enum representing the type of a trade
   * - trade: initial trade
   * - settlement: the trade is for settlement
   * - delivery: the trade is for delivery
   */
  enum trade-type {
    trade,
    settlement,
    delivery
  }
/**
   * Enum representing the trade activity
   * - open: trade is on open activity
   * - close: the trade is on close activity
   */
  enum trade-activity {
    open,
    close
  }

  /**
   * Record representing exercise balance
   * - counterparty-name: name of the counterparty
   * - pnl-description: description of the profit and loss
   * - amount: the amount of the exercised balance
   * - currency: name of the currency
   */
  record exercised-balance {
    counterparty-name: string,
    pnl-description: string,
    amount: f64,
    currency: string
  }

  /**
   * Record representing insterest payments
   * - counterparty-name: name of the counterparty
   * - pnl-description: description of the profit and loss
   * - amount: the amount of the exercised balance
   * - currency: name of the currency
   */
  record interest-payment {
    counterparty-name: string,
    pnl-description: string,
    amount: f64,
    currency: string
  }
}
